import type { RunMetadata, ProviderStatus } from "./types";

/**
 * Classifies the provider status of a run based on its metadata.
 *
 * Pure, deterministic, total: always returns exactly one ProviderStatus,
 * never throws, and the same input always produces the same output.
 */
export function classifyProvider(meta: RunMetadata): ProviderStatus {
  // Branch 1: Mock or falsy provider
  if (!meta.provider_name || meta.provider_name === "mock") {
    return { label: "Static / Mock", badge: "red" };
  }

  // Branch 2: Bedrock with generation disabled
  if (meta.provider_name === "bedrock" && !meta.provider_generation_enabled) {
    return {
      label: "Bedrock Metadata Only",
      badge: "amber",
      explanation:
        "Bedrock credentials/model selected, but no live generation steps were executed.",
    };
  }

  // Branch 3: Bedrock with generation enabled and all success conditions met
  if (meta.provider_name === "bedrock" && meta.provider_generation_enabled) {
    const hasResearch = meta.generated_steps.includes("research");
    const hasCalls = meta.bedrock_calls_made >= 1;
    const validationNotFailed = meta.bedrock_validation_passed !== false;

    if (hasResearch && hasCalls && validationNotFailed) {
      return { label: "Bedrock Live Research", badge: "green" };
    }
  }

  // Branch 4: Fallback — generation enabled but failed/incomplete
  return { label: "Bedrock Generation Failed / Incomplete", badge: "red-amber" };
}

/**
 * Determines whether a given pipeline step was generated by a live provider
 * or came from static/pre-computed data.
 *
 * Returns "generated" only if `generated_steps` includes the given step name,
 * otherwise returns "static".
 */
export function getGenerationSource(
  meta: RunMetadata,
  stepName: string
): "static" | "generated" {
  return meta.generated_steps.includes(stepName) ? "generated" : "static";
}
