"""promptfoo exporter - renders tests in promptfoo-compatible YAML format."""

from __future__ import annotations

import logging
from pathlib import Path

import yaml

from agentbattery.models import GeneratedTest

logger = logging.getLogger(__name__)


def export_promptfoo(tests: list[GeneratedTest], output_dir: Path) -> list[Path]:
    """Export tests in promptfoo-compatible YAML format (minimal/stub).

    Generates a single promptfoo configuration YAML file that references
    the generated tests as test cases.

    Args:
        tests: List of GeneratedTest objects to export.
        output_dir: Directory to write the promptfoo config to.

    Returns:
        List containing the path to the generated promptfoo config file.
    """
    output_dir.mkdir(parents=True, exist_ok=True)
    file_path = output_dir / "promptfoo_config.yaml"

    # Build promptfoo-compatible structure
    promptfoo_tests: list[dict] = []
    for test in tests:
        test_case: dict = {
            "description": test.title,
            "vars": {
                "scenario": test.setup.get("scenario", test.title),
                "trigger": test.setup.get("trigger", ""),
            },
            "assert": [],
        }

        for assertion in test.assertions:
            if assertion.startswith("must_call:"):
                test_case["assert"].append({
                    "type": "contains",
                    "value": assertion.split(":", 1)[1].strip(),
                })
            elif assertion.startswith("must_not_call:"):
                test_case["assert"].append({
                    "type": "not-contains",
                    "value": assertion.split(":", 1)[1].strip(),
                })

        # Add metadata
        test_case["metadata"] = {
            "finding_id": test.finding_id,
            "test_type": test.test_type,
            "tags": test.tags,
        }

        promptfoo_tests.append(test_case)

    config = {
        "description": "Agent safety tests generated by agentbattery",
        "providers": ["openai:gpt-4"],  # placeholder
        "tests": promptfoo_tests,
    }

    with open(file_path, "w") as f:
        yaml.dump(config, f, default_flow_style=False, sort_keys=False)

    logger.debug(f"Exported promptfoo config: {file_path}")
    return [file_path]
